IF NOT EXISTS (SELECT * FROM SYS.OBJECTS
WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[Cards]') AND TYPE IN (N'U'))
BEGIN
	CREATE TABLE [dbo].[Cards] (
		CardID			INT IDENTITY(1,1) NOT NULL,
		CardNumber		INT NOT NULL,
		DateEnd			DATE NULL,
		CustomerID		INT NULL,
		CardHolderName	NVARCHAR(50) NULL,
		CONSTRAINT [PK_Card] PRIMARY KEY ([CardID] ASC)	
	)
END